# -*- coding: utf-8 -*-
"""Untitled8.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1AQZtiPKoUlLgDtFfkU5l5VTtHZO-l6du
"""

import numpy as np

q = 4

Q = np.zeros((8,8))

for k in range(Q.shape[0]):
  for l in range(Q.shape[1]):
    Q[k][l] = 1+((1+k+l)*q)
print(Q)

V = np.array([[186,-18,15,-9,23,-9,-14,19],
              [21,-34,26,-9,-11,11,14,7],
              [-10,-24,-2,6,-18,3,-20,-1],
              [-8,-5,14,-15,-8,-3,-3,8],
              [-3,10,8,1,-11,18,18,15],
              [4,-2,-18,8,8,-4,1,-7],
              [9,1,-3,4,-1,-7,-1,-2],
              [0,-8,-2,2,1,4,-6,0]])
Y = np.round(V/Q)
print(Y)

Y_reorder = np.array([37,-2,2,-1,-3,1,-1,2,-1,0,0,0,0,0,1,0,0,0,1,0,0,0,0,0,-1,-1,0,0,1,0,0,0,0,-1,0,0,0,0,0,0,0,-1,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0])
print(Y_reorder)